### ISSUE TITLE
isAddMoreSeparateLine设置true后报错

### ISSUE THREAD

**Issue by pxim** [ParryQiu/Generate-Cnblogs-Articles-To-Markdown#2]
@ParryQiu 
 /// <param name="isAddMoreSeparateLine">在抓取到的文章 separateLineLocation（参数） 处添加分隔符，用于博客展示文章时用于抽取描述以及阅读更多使用。</param>

 #把这个参数设置成true后，
  CnblogsHelper.ExportToMarkdown(1, 5, true, "", true);
报错，如图
![error1](https://cloud.githubusercontent.com/assets/5111701/25121991/f5ec9d36-2455-11e7-9598-ce6e04f6c308.jpg)

**Comment by pxim** [comment]
hello @ParryQiu ,楼主

**Comment by ParryQiu** [comment]
的确少了一个长度的判断，已修正，感谢。
